# Generated by Django 2.2.7 on 2019-11-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medignore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='file',
        ),
        migrations.AddField(
            model_name='photo',
            name='photo_file',
            field=models.ImageField(blank=True, upload_to='medignore/'),
        ),
    ]
